
#List of affix configurations
[[affixes]]
	identifier = "adaptable"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "arctic"
	mobList = ["minecraft:enderman"]
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "dampening"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "desecrating"
	mobList = ["minecraft:enderman"]
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "enkindling"
	mobList = ["minecraft:enderman"]
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "hasty"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "infested"
	mobList = ["minecraft:enderman"]
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = false

[[affixes]]
	identifier = "knocking"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "lively"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "magnetic"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "molten"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "paralyzing"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "plagued"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "reflective"
	mobList = ["minecraft:enderman", "minecraft:blaze", "minecraft:wither_skeleton"]
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

[[affixes]]
	identifier = "shielding"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = false

[[affixes]]
	identifier = "wounding"
	mobList = []
	mobPermission = "BLACKLIST"
	minTier = 1
	enabled = true

