
#Common configurations for Atmospheric
[common]

	#Values for biome frequencies; lower = more rare. (Requires restart)
	[common.biomeWeights]
		#The frequency of Dunes; Default: 5
		dunesWeight = 6
		#The frequency of Rocky Dunes; Default: 4
		rockyDunesWeight = 5
		#The frequency of Rosewood Forests; Default: 2
		rosewoodForestWeight = 3
